#!/bin/bash
# This script will copy the needed files to the server
# With the given IP address and it will start the VUE.js service
IP=$2
USER=$1
if [[ $# -lt 2 ]]
then
	echo "Usage: ./page_deploy <server_user> <server_ip>"
else
	sudo rsync -avze "ssh" --rsync-path="sudo rsync" ./pavapp-web $USER@$IP:~
	ssh $USER@$IP '(cd ~/pavapp-web/ ; sudo yarn install --network-timeout 600000)'
fi
