#!/bin/bash
# This script configures the server based on a Raspberry

# Install packages
sudo apt update
sudo apt install -y python3-pip
sudo pip3 install Flask
sudo apt install -y nodejs
sudo apt install -y npm
sudo npm install --global yarn
sudo npm install -g @vue/cli
sudo apt upgrade -y

# Set static IP address
# On the gateway address change to your router IP address
# On the address value write the static IP address you want on your server

echo "auto eth0
iface eth0 inet static
      address 192.168.1.110
      netmask 255.255.255.0
      gateway 192.168.1.1
      dns-nameservers 4.4.4.4
      dns-nameservers 8.8.8.8" | sudo tee /etc/network/interfaces

# Set domain to connect to the Raspberry server through it
# Change pavapp to the name of the server you want to keep
# This will allow the user to connect to the page with
# name.local. For example, here you connect to the web page
# with pavapp.local

if grep "pavapp" /etc/hosts
then
    :
else
    echo "127.0.0.1	pavapp
0.0.0.0		pavapp" | sudo tee -a /etc/hosts
fi
if grep "pavapp" /etc/hostname
then
    :
else
    echo "pavapp" | sudo tee /etc/hostname
fi

#Restart the network service to commit changes
sudo service networking restart
