#!/bin/bash
# This script configures the server based on a Raspberry

# Install packages
sudo apt update
sudo apt install -y avahi-daemon
sudo apt install -y nodejs
sudo apt install -y npm
sudo npm install --global yarn
sudo npm install -g @vue/cli
sudo apt upgrade -y

